- name: Replace items to yaml file at correct indentation level
  gather_facts: 'no'
  hosts: localhost
  tasks:
   - name: Replace two items ("lx_debian_tst" and "hosts") to three items (+ "new_debian") at indentation level
     replace:
       path: /home/user/my.yml
       regexp: '^(\s*)lx_debian_tst:\n^(\s*)hosts:\n'
       replace: '\1lx_debian_tst:\n\1  hosts:\n\1    new_debian:\n'


- name: Replace items to yaml file at correct indentation level
  gather_facts: 'no'
  hosts: localhost
  tasks:
   - name: Replace two items ("lx_debian_tst" and "hosts") to three items (+ "new_debian") at indentation level
     replace:
       path: /home/user/my.yml
       regexp: '^(\s*)lx_debian_tst:\n^(\s*)hosts:\n'
       replace: '\1lx_debian_tst:\n\1  hosts:\n\1    new_debian:\n'


- name: Replace items to yaml file at correct indentation level
  gather_facts: 'no'
  hosts: localhost
  tasks:
   - name: Replace two items ("lx_debian_tst" and "hosts") to three items (+ "new_debian") at indentation level
     replace:
       path: /home/user/my.yml
       regexp: '^(\s*)lx_debian_tst:\n^(\s*)hosts:\n'
       replace: '\1lx_debian_tst:\n\1  hosts:\n\1    new_debian:\n'
#####
